// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQD3WvLspjqIZfnfNyIUaFiU20pP06d40',
    appId: '1:619193314973:web:73b8a172bbbe060f80ae74',
    messagingSenderId: '619193314973',
    projectId: 'pgappnotificaciones',
    authDomain: 'pgappnotificaciones.firebaseapp.com',
    storageBucket: 'pgappnotificaciones.appspot.com',
    measurementId: 'G-DXJY0CNYWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDafKN2lB0-PF9I3a3lbwVVZZ_MyVMadTQ',
    appId: '1:619193314973:android:2c626455e2c293f180ae74',
    messagingSenderId: '619193314973',
    projectId: 'pgappnotificaciones',
    storageBucket: 'pgappnotificaciones.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALGy0HvubVZTFUyfTTHssd09XX7gI2I8o',
    appId: '1:619193314973:ios:d8c315d1c449483480ae74',
    messagingSenderId: '619193314973',
    projectId: 'pgappnotificaciones',
    storageBucket: 'pgappnotificaciones.appspot.com',
    iosBundleId: 'com.example.proyectoGradoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALGy0HvubVZTFUyfTTHssd09XX7gI2I8o',
    appId: '1:619193314973:ios:d8c315d1c449483480ae74',
    messagingSenderId: '619193314973',
    projectId: 'pgappnotificaciones',
    storageBucket: 'pgappnotificaciones.appspot.com',
    iosBundleId: 'com.example.proyectoGradoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQD3WvLspjqIZfnfNyIUaFiU20pP06d40',
    appId: '1:619193314973:web:fbdef1d265e0cd4980ae74',
    messagingSenderId: '619193314973',
    projectId: 'pgappnotificaciones',
    authDomain: 'pgappnotificaciones.firebaseapp.com',
    storageBucket: 'pgappnotificaciones.appspot.com',
    measurementId: 'G-GMX8F3DF8D',
  );
}
